apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: back
  template:
    metadata:
      labels:
        components: back
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_HOSTNAME
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: api-pvc
