apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rmq
  template:
    metadata:
      labels:
        components: rmq
    spec:
      containers:
        - name: rmq-app
          image: rabbitmq:3.7.3
          ports:
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: RABBITMQ_DEFAULT_PASS
          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"
          volumeMounts:
            - name: rmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rmq-data
          persistentVolumeClaim:
            claimName: rmq-pvc
